### ISSUE TITLE
Workaround for CF7 5.4 changes

### ISSUE THREAD

**Issue by aurovrata** [maximum-software/pdf-forms-for-contact-form-7#10]
Greetings Alex,

I am the developer of the Smart Grid-layout extension for CF7.

I saw your recent [issue](https://github.com/takayukister/contact-form-7/issues/344) raised on the CF7 plugin which I fully support.

However, I am unable to contribute to that discussion as the author has blocked my account on the CF7 repo, so I thought I would share a possible workaround for your plugin (which is fantastic btw! :).  I have several users of my plugin who also use yours and have raised question on the Smart Grid support forum.

The Smart Grid allows repetitive field constructs, but CF7 only validates/handle the initial field.  The Smart Grid uses the CF7 functionality to validate/handle the others.  However, with  file fields this is no longer possible.
 
I managed to solve the problem (temporarily, I hope Takayuki-san will deliver on your request) by storing the validated files into the `posted_data` array of the `WPCF7_Submission` object, and then subsequently hooking into the CF7 notification email to attach any files parametrised for that form.

it involves the following steps:

1. Hooking into  `wpcf7_posted_data` process to keep a reference to the posted data,
```php
add_filter('wpcf7_posted_data','track_posted_data');
function track_posted_data($data){
  $cf7form = WPCF7_ContactForm::get_current();
  if($cf7form){
    $this->posted_data[$cf7form->id] = &$data; 
    //I use classes for my plugin, hence the $this. You can store a refernce in a global scope otherwise.
  }
  return $data;
}
```
2.  hooking into the `wpcf7_validate`  and proceed to use the CF7  `wpcf7_unship_uploaded_file()` function to validate files prior to the CF7 plugin itself (the new file validation code is executed after the validation of the data submission).

```php
add_filter('wpcf7_validate', 'validate_files');
function validate_files($result){
  $contact_form = WPCF7_ContactForm::get_current();
  if(!$contact_form) return $result;
  $tags = $contact_form->scan_form_tags( array(
   'feature' => 'file-uploading',
  ) );
  foreach($tags as $tag){
    if(!isset($_FILES[$tag['name']])) continue;
    $file = $_FILES[$tag['name']];
    $args = array(
      'tag' => $tag,
      'name' => $tag->name,
      'required' => $tag->is_required(),
      'filetypes' => $tag->get_option( 'filetypes' ),
      'limit' => $tag->get_limit_option(),
    );
    $new_files = wpcf7_unship_uploaded_file( $file, $args );

    $result = apply_filters("wpcf7_validate_{$tag->type}", $result, $tag,
      array(
        'uploaded_files' => $new_files,
      ));
    //store files into the referenced data.
    $this->posted_data[$cf7form->id][$tag->name] = $new_files;
  }
  if($result->is_valid()){
      //this is where you can push your own files
      $this->posted_data[$cf7form->id]['my-custom-file'] = array($path_to_new_file);
  }
  return $result;
}
```
NOTE: `wpcf7_unship_uploaded_file()` will actually move the $_FILES tmp files to the `wp-content/uploads/wpcf7` folder, so the CF7 plugin will not be able to actually insert the file into the submission object, hence step 3 below.

3. Finally, hook into the notification mail components to attach any files required.

```php
add_filter('wpcf7_mail_components','attach_files',10,3);
function attach_files($components, $cf7form, $cf7mail){
  $submission = WPCF7_Submission::get_instance();
  $tags = $cf7form->scan_form_tags(array(
     'feature' => 'file-uploading',
  ) );
  $template = $cf7mail->get( 'attachments' );
  $attachments = &$components['attachments'];
  foreach ( $tags as $tag ) {
      $name = $tag['name'];
      if ( false === strpos( $template, "[${name}]" ) )  continue; //not attached.
     
      $data = $submission->get_posted_data($name); //at this point the data has all our files.
      if(empty($data)) continue;  //no file uploaded in this case
      foreach($data as $path){ //possible multiple files 
        if(!in_array($path, $attachments)) $attachments[] = $path; //male sure it hasn't been attached before by another plugin.
      }
  }
  return $components;
}
```

I have tested a version of this on my plugin successfully.  I have cut and paste the above with some changes from my code, so it may not work as is (apologies if doesn't) but this should give you the basic idea.  In case you have any queries, I'd be happy to help.

**Comment by maxguru** [comment]
Wow, thanks for the input. I didn't know about this 'wpcf7_mail_components' hook.

I actually don't really need to do most of this stuff. The only thing I need to do is save the attachments into a variable in my 'wpcf7_before_send_mail' handler and then use it in the 'wpcf7_mail_components' handler.

I made the fix. Check it out if you like: https://github.com/maximum-software/pdf-forms-for-contact-form-7/commit/b61fa0b1e9ea54ffccd2e8d2771e63cf147ba7ea. I'll do more testing and deploy it a bit later.

**Comment by aurovrata** [comment]
great, glad you got it working :)
